var questions = 3;
var questionsLeft = ' [' + questions + ' questions left]';
var persona = prompt("Please enter a name:", "Goofy" + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var personb = prompt("Please enter a second name:", "Hobbes" + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var personc = prompt("Please enter a third name", "Jean" + questionsLeft);
alert('All done. Ready for the message?');
var sentence = "Three people are on the run from the police:" + persona;
sentence += "," + personb;
sentence += "," + personc;
sentence += ". They come across a barn run inside to hide. They see a group of cows, chickens, and a potato sack on the floor." + persona;
document.write(sentence);
